version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_TTS_KEY=${GOOGLE_TTS_KEY:-}
    volumes:
      - ./output:/app/output
    command: uvicorn researchtopodcast.api.main:app --host 0.0.0.0 --port 8000 --reload

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    command: |
      sh -c "echo 'events { worker_connections 1024; }
      http {
        upstream api {
          server api:8000;
        }
        server {
          listen 80;
          location / {
            proxy_pass http://api;
            proxy_set_header Host \$$host;
            proxy_set_header X-Real-IP \$$remote_addr;
          }
        }
      }' > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
